import { useEffect, useState } from 'react'
import { ArrowLeft, ArrowUpRight, BarChart3, Check, ChevronRight, Download, FileText, LoaderCircle, Play, Plus, Save, ShieldCheck, UploadCloud, X, Zap } from 'lucide-react'
import { listReports, removeReport, saveReport } from './lib/storage'

const API_URL = import.meta.env.VITE_AGENT_API_URL || 'http://127.0.0.1:8000'
const DEFAULT_QUERY = 'Analyze revenue by product category and identify return risks'
const STEPS = ['Profile dataset', 'Build analytical plan', 'Generate code', 'Run isolated analysis', 'Synthesize decision brief']

function Logo() { return <div className="logo"><i /><i /><i /><strong>DataSnap</strong></div> }
function dateLabel(value) { return value ? new Date(value).toLocaleDateString([], { month: 'short', day: 'numeric', year: 'numeric' }) : 'Just now' }

export default function App() {
  const [page, setPage] = useState(window.location.pathname.startsWith('/reports') ? 'reports' : window.location.pathname.startsWith('/report/') ? 'report' : window.location.pathname === '/analyze' ? 'analyze' : 'landing')
  const [reportId, setReportId] = useState(window.location.pathname.split('/').pop())
  const [reports, setReports] = useState([])
  const [report, setReport] = useState(null)
  const [file, setFile] = useState(null)
  const [query, setQuery] = useState(DEFAULT_QUERY)
  const [running, setRunning] = useState(false)
  const [step, setStep] = useState(0)
  const [error, setError] = useState('')
  const [quota, setQuota] = useState(null)

  useEffect(() => { listReports().then(items => { setReports(items); if (page === 'report') setReport(items.find(item => item.analysis_id === reportId)) }) }, [])
  useEffect(() => { const onPop = () => { const path = window.location.pathname; setPage(path.startsWith('/reports') ? 'reports' : path.startsWith('/report/') ? 'report' : path === '/analyze' ? 'analyze' : 'landing'); setReportId(path.split('/').pop()) }; window.addEventListener('popstate', onPop); return () => window.removeEventListener('popstate', onPop) }, [])

  function navigate(next, id = '') { const path = id ? `/report/${id}` : next === 'analyze' ? '/analyze' : next === 'reports' ? '/reports' : '/'; window.history.pushState({}, '', path); setPage(next); if (id) setReportId(id) }
  function openReport(item) { setReport(item); navigate('report', item.analysis_id) }

  async function runAnalysis() {
    if (!file) return setError('Choose a dataset before continuing.')
    if (!query.trim()) return setError('Add a business question before continuing.')
    setRunning(true); setError(''); setStep(0)
    const payload = new FormData(); payload.append('query', query.trim()); payload.append('dataset', file); payload.append('provider', 'gemini')
    const timer = setInterval(() => setStep(current => Math.min(current + 1, STEPS.length - 1)), 1500)
    try {
      const response = await fetch(`${API_URL}/api/v1/analyze`, { method: 'POST', body: payload, credentials: 'include' })
      const body = await response.json()
      setQuota({ remaining: response.headers.get('X-RateLimit-Remaining'), limit: response.headers.get('X-RateLimit-Limit') || '5' })
      if (!response.ok) throw new Error(body.detail || body.error?.message || 'Analysis could not be completed.')
      setReport(body); navigate('report', body.analysis_id)
    } catch (requestError) { setError(requestError.message) } finally { clearInterval(timer); setRunning(false) }
  }

  async function deleteReport(id) { await removeReport(id); const next = await listReports(); setReports(next); if (report?.analysis_id === id) { setReport(null); navigate('reports') } }
  function download(name, content, type) { const url = URL.createObjectURL(new Blob([content], { type })); const anchor = document.createElement('a'); anchor.href = url; anchor.download = name; anchor.click(); URL.revokeObjectURL(url) }

  return <div className="site-shell"><header className="site-nav"><button className="brand-button" onClick={() => navigate('landing')}><Logo /></button><nav><button className={page === 'analyze' ? 'active' : ''} onClick={() => navigate('analyze')}>Analyze</button><button className={page === 'reports' || page === 'report' ? 'active' : ''} onClick={() => navigate('reports')}>Reports <span>{reports.length}</span></button></nav><div className="nav-actions"><span className="privacy"><ShieldCheck size={14} /> Private by default</span><span className="quota">{quota ? `${quota.remaining}/${quota.limit} analyses left` : '5 analyses / hour'}</span></div></header>
    {page === 'landing' && <Landing onStart={() => navigate('analyze')} onReports={() => navigate('reports')} />}
    {page === 'analyze' && <Analyze file={file} setFile={setFile} query={query} setQuery={setQuery} running={running} step={step} error={error} onRun={runAnalysis} onReports={() => navigate('reports')} />}
    {page === 'reports' && <Reports reports={reports} onOpen={openReport} onDelete={deleteReport} onNew={() => navigate('analyze')} />}
    {page === 'report' && <ReportPage report={report || reports.find(item => item.analysis_id === reportId)} saved={reports.some(item => item.analysis_id === reportId)} onSave={async item => { await saveReport(item); setReports(await listReports()) }} onBack={() => navigate('reports')} download={download} />}
  </div>
}

function Landing({ onStart, onReports }) {
  return <main className="landing"><section className="hero"><div className="hero-copy"><p className="eyebrow"><span /> AI-POWERED DECISION INTELLIGENCE</p><h1>Find the signal<br /><em>inside your data.</em></h1><p className="hero-sub">Upload a dataset, ask a business question, and get a clear decision brief backed by machine-verified evidence.</p><div className="hero-actions"><button className="primary-cta" onClick={onStart}>Start an analysis <ArrowUpRight size={17} /></button><button className="text-button" onClick={onReports}>View saved reports <ChevronRight size={15} /></button></div><div className="hero-trust"><span><ShieldCheck size={15} /> Isolated execution</span><span><Check size={15} /> Evidence-first output</span><span><Zap size={15} /> Built for fast answers</span></div></div><div className="hero-visual"><div className="visual-top"><span>LIVE SIGNAL</span><span>ANALYSIS READY</span></div><div className="signal-card"><div className="signal-header"><div><small>REVENUE MOMENTUM</small><strong>+32.8%</strong></div><span className="signal-up">↗</span></div><div className="signal-chart"><i /><i /><i /><i /><i /><i /><i /><i /><i /></div><div className="chart-axis"><span>JAN</span><span>APR</span><span>JUL</span><span>OCT</span></div></div><div className="floating-card"><div className="mini-icon"><BarChart3 size={16} /></div><div><strong>Decision brief</strong><small>6 verified insights</small></div><Check size={16} /></div><div className="visual-caption"><span>01</span><p>From raw rows to a decision-ready view.</p></div></div></section><section className="landing-strip"><div><strong>01</strong><span>Upload your data</span></div><div><strong>02</strong><span>Ask the question</span></div><div><strong>03</strong><span>Review the evidence</span></div></section></main>
}

function Analyze({ file, setFile, query, setQuery, running, step, error, onRun, onReports }) {
  const chooseFile = event => setFile(event.target.files?.[0] || null)
  return <main className="workspace"><div className="workspace-intro"><div><p className="eyebrow"><span /> NEW ANALYSIS</p><h1>What decision are you making?</h1><p>Bring the data. DataSnap will structure the analysis and return the evidence.</p></div><button className="text-button" onClick={onReports}>Open saved reports <ChevronRight size={15} /></button></div><div className="analyze-grid"><section className="input-panel"><div className="panel-step"><span>01</span><div><strong>Dataset</strong><small>CSV, XLSX, Parquet, TSV, JSON or JSONL</small></div></div><div className={`upload-box ${file ? 'selected' : ''}`} onDragOver={event => event.preventDefault()} onDrop={event => { event.preventDefault(); setFile(event.dataTransfer.files[0]) }}>{file ? <div className="file-selected"><div className="file-type"><FileText size={21} /></div><div><strong>{file.name}</strong><span>{(file.size / 1024).toFixed(1)} KB · Ready to analyze</span></div><label className="change-file">Change<input type="file" accept=".csv,.xlsx,.parquet,.tsv,.json,.jsonl" onChange={chooseFile} /></label><button className="remove-file" onClick={() => setFile(null)} aria-label="Remove selected file"><X size={16} /></button></div> : <><div className="upload-symbol"><UploadCloud size={23} /></div><strong>Drop your dataset here</strong><span>or browse from your computer</span><input type="file" accept=".csv,.xlsx,.parquet,.tsv,.json,.jsonl" onChange={chooseFile} /></>}</div><div className="panel-step question-step"><span>02</span><div><strong>Business question</strong><small>Be specific about the decision you need to make</small></div></div><textarea className="question-box" value={query} onChange={event => setQuery(event.target.value)} maxLength={500} /><div className="input-footer"><span className="fallback-note"><Zap size={15} /> Gemini primary + automatic fallback</span><button className="primary-cta small" onClick={onRun} disabled={running}>{running ? <><LoaderCircle className="spin" size={16} /> Analyzing</> : <><Play size={16} fill="currentColor" /> Run analysis</>}</button></div>{error && <div className="error-line"><X size={15} /><div><strong>Analysis could not be completed</strong><span>{error}</span><button onClick={onRun}>Try again</button></div></div>}</section><aside className="process-panel"><p className="eyebrow">YOUR ANALYSIS</p><h2>{running ? 'Building your brief' : 'A clear path to clarity'}</h2><div className="process-list">{STEPS.map((item, index) => <div className={`process-row ${step > index ? 'done' : ''} ${running && step === index ? 'current' : ''}`} key={item}><span>{step > index ? <Check size={12} /> : `0${index + 1}`}</span><strong>{item}</strong></div>)}</div><div className="process-note"><ShieldCheck size={17} /><p>Your dataset is executed in an isolated runtime. Reports are saved only when you choose to save them.</p></div></aside></div></main>
}

function AnalyzeLegacy({ file, setFile, query, setQuery, model, setModel, running, step, error, onRun, onReports }) {
  return <main className="workspace"><div className="workspace-intro"><div><p className="eyebrow"><span /> NEW ANALYSIS</p><h1>What decision are you making?</h1><p>Bring the data. Lumen will structure the analysis and return the evidence.</p></div><button className="text-button" onClick={onReports}>Open saved reports <ChevronRight size={15} /></button></div><div className="analyze-grid"><section className="input-panel"><div className="panel-step"><span>01</span><div><strong>Dataset</strong><small>CSV, XLSX, Parquet, TSV, JSON or JSONL</small></div></div><div className={`upload-box ${file ? 'selected' : ''}`} onDragOver={event => event.preventDefault()} onDrop={event => { event.preventDefault(); setFile(event.dataTransfer.files[0]) }}><div className="upload-symbol"><UploadCloud size={23} /></div><strong>{file ? file.name : 'Drop your dataset here'}</strong><span>{file ? `${(file.size / 1024).toFixed(1)} KB ready to analyze` : 'or browse from your computer'}</span><input type="file" accept=".csv,.xlsx,.parquet,.tsv,.json,.jsonl" onChange={event => setFile(event.target.files?.[0] || null)} /></div><div className="panel-step question-step"><span>02</span><div><strong>Business question</strong><small>Be specific about the decision you need to make</small></div></div><textarea className="question-box" value={query} onChange={event => setQuery(event.target.value)} maxLength={500} /><div className="input-footer"><label><Zap size={15} /><select value={model} onChange={event => setModel(event.target.value)}><option value="gemini-3.1-flash-lite">Gemini 3.1 Flash Lite</option><option value="gemini-3.5-flash-lite">Gemini 3.5 Flash Lite</option><option value="gemini-2.5-flash-lite">Gemini 2.5 Flash Lite</option></select></label><button className="primary-cta small" onClick={onRun} disabled={running}>{running ? <><LoaderCircle className="spin" size={16} /> Analyzing</> : <><Play size={16} fill="currentColor" /> Run analysis</>}</button></div>{error && <div className="error-line"><X size={15} /> {error}</div>}</section><aside className="process-panel"><p className="eyebrow">YOUR ANALYSIS</p><h2>{running ? 'Building your brief' : 'A clear path to clarity'}</h2><div className="process-list">{STEPS.map((item, index) => <div className={`process-row ${step > index ? 'done' : ''} ${running && step === index ? 'current' : ''}`} key={item}><span>{step > index ? <Check size={12} /> : `0${index + 1}`}</span><strong>{item}</strong></div>)}</div><div className="process-note"><ShieldCheck size={17} /><p>Your dataset is executed in an isolated runtime. Reports are saved only when you choose to save them.</p></div></aside></div></main>
}

function Reports({ reports, onOpen, onDelete, onNew }) {
  return <main className="reports-page"><div className="page-heading"><div><p className="eyebrow"><span /> REPORT LIBRARY</p><h1>Your saved intelligence.</h1><p>Only reports you explicitly saved live here, in this browser.</p></div><button className="primary-cta small" onClick={onNew}><Plus size={16} /> New analysis</button></div>{reports.length === 0 ? <div className="empty-library"><FileText size={25} /><h2>No saved reports yet</h2><p>Run an analysis, then save the result when you are ready to keep it.</p><button className="text-button" onClick={onNew}>Start your first analysis <ArrowUpRight size={15} /></button></div> : <div className="report-list">{reports.map(item => <article className="report-row" key={item.analysis_id}><button onClick={() => onOpen(item)}><span className="report-mark"><BarChart3 size={18} /></span><span><strong>{item.answers_to_query?.slice(0, 85) || 'Decision brief'}</strong><small>{dateLabel(item.saved_at)} · {item.grounding?.data_quality?.row_count || 0} rows analyzed</small></span></button><span className="report-status"><Check size={13} /> Saved</span><button className="delete-button" onClick={() => onDelete(item.analysis_id)} aria-label="Delete report"><X size={16} /></button></article>)}</div>}</main>
}

function OldReportPage({ report, saved, onSave, onBack, download }) {
  if (!report) return <main className="reports-page"><button className="text-button" onClick={onBack}><ArrowLeft size={15} /> Back to reports</button><div className="empty-library"><FileText size={25} /><h2>Report not found</h2><p>This report is not available in this browser.</p></div></main>
  return <main className="report-page"><div className="report-page-nav"><button className="text-button" onClick={onBack}><ArrowLeft size={15} /> All reports</button><div className="report-actions"><span className="verified"><Check size={13} /> Verified metrics</span><button className="save-button" onClick={() => onSave(report)} disabled={saved}><Save size={15} /> {saved ? 'Saved locally' : 'Save report'}</button><button className="outline-button" onClick={() => download('lumen-report.md', report.markdown_report || '', 'text/markdown')}><FileText size={15} /> Markdown</button><button className="outline-button" onClick={() => download('lumen-report.html', report.html_report || '', 'text/html')}><Download size={15} /> HTML</button></div></div><div className="report-paper"><div className="report-paper-head"><div><p className="eyebrow"><span /> ANALYTICAL DECISION REPORT</p><h1>Decision brief</h1><p>Evidence prepared from {report.grounding?.data_quality?.row_count || 0} rows of uploaded data.</p></div><span className="report-stamp"><ShieldCheck size={16} /> Machine verified</span></div><div className="report-content"><div className="report-lead"><span>EXECUTIVE SUMMARY</span><p>{report.executive_summary}</p></div><div className="report-answer"><span>ANSWER TO YOUR QUESTION</span><p>{report.answers_to_query}</p></div><div className="report-columns"><section><h2>Statistical insights</h2><ul>{(report.statistical_insights || []).map(item => <li key={item}>{item}</li>)}</ul></section><section><h2>Recommended actions</h2><ul>{(report.recommended_actions || []).map(item => <li key={item}>{item}</li>)}</ul></section></div></div><div className="report-embed"><iframe title="Full analytical decision report" srcDoc={report.html_report || '<p>No formatted report available.</p>'} /></div></div></main>
}

function ReportPage({ report, saved, onSave, onBack, download }) {
  const [tab, setTab] = useState('overview')
  if (!report) return <main className="reports-page"><button className="text-button" onClick={onBack}><ArrowLeft size={15} /> Back to reports</button><div className="empty-library"><FileText size={25} /><h2>Report not found</h2><p>This report is not available in this browser.</p></div></main>
  const metrics = report.metrics || {}
  const metricRows = Object.entries(metrics)
  return <main className="report-page"><div className="report-page-nav"><button className="text-button" onClick={onBack}><ArrowLeft size={15} /> All reports</button><div className="report-actions"><span className="verified"><Check size={13} /> Verified metrics</span><button className="save-button" onClick={() => onSave(report)} disabled={saved}><Save size={15} /> {saved ? 'Saved locally' : 'Save report'}</button><button className="outline-button" onClick={() => download('lumen-report.md', report.markdown_report || '', 'text/markdown')}><FileText size={15} /> Markdown</button><button className="outline-button" onClick={() => download('lumen-report.html', report.html_report || '', 'text/html')}><Download size={15} /> HTML</button></div></div><div className="report-paper"><div className="report-paper-head"><div><p className="eyebrow"><span /> ANALYTICAL DECISION REPORT</p><h1>Decision brief</h1><p>Evidence prepared from {report.grounding?.data_quality?.row_count || 0} rows of uploaded data.</p></div><span className="report-stamp"><ShieldCheck size={16} /> Machine verified</span></div><div className="report-tabs">{[['overview', 'Overview'], ['insights', 'Insights & actions'], ['visuals', 'Visual evidence'], ['metrics', 'Verified metrics'], ['details', 'Run details']].map(([id, label]) => <button className={tab === id ? 'active' : ''} onClick={() => setTab(id)} key={id}>{label}</button>)}</div><div className="report-content">
    {tab === 'overview' && <><div className="report-lead"><span>EXECUTIVE SUMMARY</span><p>{report.executive_summary}</p></div><div className="report-answer"><span>ANSWER TO YOUR QUESTION</span><p>{report.answers_to_query}</p></div><div className="overview-cards"><div><small>ROWS ANALYZED</small><strong>{report.grounding?.data_quality?.row_count || '—'}</strong></div><div><small>METRICS VERIFIED</small><strong>{report.grounding?.metric_count || metricRows.length}</strong></div><div><small>VISUALS GENERATED</small><strong>{report.charts?.length || 0}</strong></div></div></>}
    {tab === 'insights' && <div className="report-columns full"><section><p className="section-label">STATISTICAL INSIGHTS</p><h2>What the data says</h2><ul>{(report.statistical_insights || []).map(item => <li key={item}>{item}</li>)}</ul></section><section><p className="section-label">RECOMMENDED ACTIONS</p><h2>What to do next</h2><ul>{(report.recommended_actions || []).map(item => <li key={item}>{item}</li>)}</ul></section></div>}
    {tab === 'visuals' && <div className="visual-report-grid">{(report.charts || []).map((chart, index) => <figure key={`${index}-${chart.slice(0, 20)}`}><img src={`data:image/png;base64,${chart}`} alt={`Analysis visualization ${index + 1}`} /><figcaption>Visualization {String(index + 1).padStart(2, '0')}</figcaption></figure>)}</div>}
    {tab === 'metrics' && <div className="metrics-reader">{metricRows.map(([key, value]) => <section key={key}><div className="metric-heading"><span>{key.replaceAll('_', ' ')}</span><em>verified</em></div>{Array.isArray(value) && value.length && typeof value[0] === 'object' ? <div className="metric-table-wrap"><table><thead><tr>{Object.keys(value[0]).map(column => <th key={column}>{column.replaceAll('_', ' ')}</th>)}</tr></thead><tbody>{value.map((row, index) => <tr key={index}>{Object.values(row).map((cell, cellIndex) => <td key={cellIndex}>{typeof cell === 'number' ? Number(cell.toFixed(4)) : String(cell)}</td>)}</tr>)}</tbody></table></div> : <strong className="metric-number">{typeof value === 'number' ? Number(value.toFixed(6)) : JSON.stringify(value)}</strong>}</section>)}</div>}
    {tab === 'details' && <div className="details-reader"><div><small>ANALYSIS ID</small><code>{report.analysis_id}</code></div><div><small>PROVIDER</small><strong>{report.grounding?.provenance?.provider || 'Gemini'}</strong></div><div><small>MODEL</small><strong>{report.grounding?.provenance?.model || 'Primary with automatic fallback'}</strong></div><div><small>DATA QUALITY</small><strong>{report.grounding?.data_quality?.status || 'Reviewed'}</strong></div><div><small>DECISION STATUS</small><strong>Pending human review</strong></div></div>}
  </div></div></main>
}

function LegacyReportPage({ report, saved, onSave, onBack, download }) {
  if (!report) return <main className="reports-page"><button className="text-button" onClick={onBack}><ArrowLeft size={15} /> Back to reports</button><div className="empty-library"><FileText size={25} /><h2>Report not found</h2><p>This report may have been removed from local storage.</p></div></main>
  return <main className="report-page"><div className="report-page-nav"><button className="text-button" onClick={onBack}><ArrowLeft size={15} /> All reports</button><div className="report-actions"><span className="verified"><Check size={13} /> Verified metrics</span><button className="outline-button" onClick={() => download('lumen-report.md', report.markdown_report || '', 'text/markdown')}><FileText size={15} /> Markdown</button><button className="outline-button" onClick={() => download('lumen-report.html', report.html_report || '', 'text/html')}><Download size={15} /> HTML</button></div></div><div className="report-paper"><div className="report-paper-head"><div><p className="eyebrow"><span /> ANALYTICAL DECISION REPORT</p><h1>Decision brief</h1><p>Evidence prepared from {report.grounding?.data_quality?.row_count || 0} rows of uploaded data.</p></div><span className="report-stamp"><ShieldCheck size={16} /> Machine verified</span></div><div className="report-content"><div className="report-lead"><span>EXECUTIVE SUMMARY</span><p>{report.executive_summary}</p></div><div className="report-answer"><span>ANSWER TO YOUR QUESTION</span><p>{report.answers_to_query}</p></div><div className="report-columns"><section><h2>Statistical insights</h2><ul>{(report.statistical_insights || []).map(item => <li key={item}>{item}</li>)}</ul></section><section><h2>Recommended actions</h2><ul>{(report.recommended_actions || []).map(item => <li key={item}>{item}</li>)}</ul></section></div></div><div className="report-embed"><iframe title="Full analytical decision report" srcDoc={report.html_report || '<p>No formatted report available.</p>'} /></div></div></main>
}
