"""Stage 4: Isolated Execution Runtime.

Executes generated Python code in a sandboxed child subprocess with
captured stdout, stderr, timeout guardrails, and structured artifact extraction.
"""

import sys
import json
import subprocess
import tempfile
import ast
import os
import resource
from pathlib import Path
from typing import Optional
from .contracts import ExecutionResult


_ALLOWED_IMPORTS = {"base64", "io", "json", "matplotlib", "pathlib", "polars", "scipy"}
_BLOCKED_CALLS = {"eval", "exec", "open", "__import__", "system", "popen", "run", "Popen"}


def _validate_generated_code(code_content: str) -> None:
    """Reject filesystem, process, and network primitives before execution."""
    try:
        tree = ast.parse(code_content)
    except SyntaxError as error:
        raise ValueError(f"Generated code is not valid Python: {error}") from error
    for node in ast.walk(tree):
        if isinstance(node, (ast.Import, ast.ImportFrom)):
            if isinstance(node, ast.Import):
                modules = [alias.name.split(".")[0] for alias in node.names]
            else:
                modules = [(node.module or "").split(".")[0]]
            if any(module not in _ALLOWED_IMPORTS for module in modules):
                raise ValueError("Generated code imports a module outside the analytics allowlist.")
        if isinstance(node, ast.Call) and isinstance(node.func, ast.Name) and node.func.id in _BLOCKED_CALLS:
            raise ValueError(f"Generated code calls blocked primitive '{node.func.id}'.")
        if isinstance(node, ast.Attribute) and node.attr in {"system", "popen", "Popen"}:
            raise ValueError("Generated code contains a blocked process primitive.")


def _limit_child_process() -> None:
    """Apply Unix resource limits to the generated-code child process."""
    resource.setrlimit(resource.RLIMIT_CPU, (60, 60))
    resource.setrlimit(resource.RLIMIT_AS, (2 * 1024 * 1024 * 1024, 2 * 1024 * 1024 * 1024))
    resource.setrlimit(resource.RLIMIT_NOFILE, (64, 64))


def execute_sandboxed_code(
    code_content: str,
    dataset_path: str,
    scratch_dir: Optional[Path] = None,
    timeout_seconds: int = 45
) -> ExecutionResult:
    """Execute Python code in an isolated subprocess.
    
    Args:
        code_content: Python source code generated by the LLM.
        dataset_path: Path to dataset to provide to the script.
        scratch_dir: Directory to place ephemeral scripts and artifact files.
        timeout_seconds: Maximum allowed execution time before SIGTERM/SIGKILL.
        
    Returns:
        ExecutionResult object with execution status, metrics, and base64 charts.
    """
    try:
        _validate_generated_code(code_content)
    except ValueError as error:
        return ExecutionResult(
            success=False,
            stderr=str(error),
            return_code=-1,
            error_message=str(error),
        )
    temporary_directory = None
    if scratch_dir is None:
        temporary_directory = tempfile.TemporaryDirectory(prefix="ai-agent-")
        scratch_dir = Path(temporary_directory.name)
    scratch_dir.mkdir(parents=True, exist_ok=True)
    script_path = scratch_dir / "runner.py"
    output_json_path = scratch_dir / "result.json"
    
    # Prepend configuration metadata / environment constants into script
    # This guarantees the script knows where to find the dataset and where to save output
    header = f"""# Auto-generated by Data Analytics AI Agent Runtime
import sys
import json
import base64
import io
import polars as pl
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from scipy import stats

DATASET_PATH = r"{Path(dataset_path).resolve()}"
OUTPUT_JSON_PATH = r"{output_json_path.resolve()}"

# Ensure output dictionary exists
__AGENT_OUTPUT__ = {{
    "metrics": {{}},
    "base64_charts": [],
    "summary": ""
}}

def save_current_figure_to_base64():
    buf = io.BytesIO()
    plt.tight_layout()
    plt.savefig(buf, format='png', dpi=150)
    buf.seek(0)
    b64 = base64.b64encode(buf.read()).decode('utf-8')
    __AGENT_OUTPUT__["base64_charts"].append(b64)
    plt.close()

"""

    footer = f"""
# Write execution result contract
with open(OUTPUT_JSON_PATH, "w", encoding="utf-8") as f:
    json.dump(__AGENT_OUTPUT__, f, indent=2, default=str)
"""

    full_code = header + "\n" + code_content + "\n" + footer
    script_path.write_text(full_code, encoding="utf-8")
    
    try:
        safe_env = {
            "PATH": os.environ.get("PATH", ""),
            "PYTHONPATH": "",
            "MPLCONFIGDIR": str(scratch_dir),
            "POLARS_MAX_THREADS": "1",
            "RAYON_NUM_THREADS": "1",
            "OMP_NUM_THREADS": "1",
            "OPENBLAS_NUM_THREADS": "1",
            "MKL_NUM_THREADS": "1",
        }
        run_kwargs = {
            "capture_output": True,
            "text": True,
            "timeout": timeout_seconds,
            "cwd": str(scratch_dir),
            "env": safe_env,
        }
        if os.name == "posix":
            run_kwargs["preexec_fn"] = _limit_child_process
        proc = subprocess.run(
            [sys.executable, "-I", str(script_path)],
            **run_kwargs,
        )
        
        stdout = proc.stdout
        stderr = proc.stderr
        return_code = proc.returncode
        
        if return_code != 0:
            error_msg = f"Process failed with exit code {return_code}.\nStderr:\n{stderr}\nStdout:\n{stdout}"
            return ExecutionResult(
                success=False,
                stdout=stdout,
                stderr=stderr,
                return_code=return_code,
                error_message=error_msg
            )
            
        if not output_json_path.exists():
            return ExecutionResult(
                success=False,
                stdout=stdout,
                stderr=stderr,
                return_code=return_code,
                error_message="Runtime succeeded but output artifact JSON was not produced."
            )
            
        with open(output_json_path, "r", encoding="utf-8") as f:
            artifact_data = json.load(f)
            
        metrics = artifact_data.get("metrics", {})
        base64_charts = artifact_data.get("base64_charts", [])
        
        return ExecutionResult(
            success=True,
            stdout=stdout,
            stderr=stderr,
            return_code=0,
            metrics=metrics,
            base64_charts=base64_charts
        )
        
    except subprocess.TimeoutExpired:
        return ExecutionResult(
            success=False,
            stdout="",
            stderr=f"Execution timed out after {timeout_seconds} seconds.",
            return_code=-1,
            error_message=f"Timeout limit ({timeout_seconds}s) exceeded."
        )
    except (OSError, json.JSONDecodeError, ValueError) as e:
        return ExecutionResult(
            success=False,
            stdout="",
            stderr=str(e),
            return_code=-1,
            error_message=f"Subprocess runner invocation failed: {e}"
        )
    finally:
        if temporary_directory is not None:
            temporary_directory.cleanup()
